first_number = float(input("Enter the first number: "))
second_number = float(input("Enter the second number: "))

print(f"{first_number} + {second_number} = {first_number + second_number}")
print(f"{first_number} - {second_number} = {first_number - second_number}")
print(f"{first_number} * {second_number} = {first_number * second_number}")
print(f"{first_number} / {second_number} = {first_number / second_number}")
print(f"{first_number} // {second_number} = {first_number // second_number}")
print(f"{first_number} % {second_number} = {first_number % second_number}")
print(f"{first_number} ** {second_number} = {first_number ** second_number}")